version: '3.8' 

services:
  traffic-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=deuser
      - MYSQL_PASSWORD=default@2025!
      - MYSQL_DBNAME=traffic_db
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json 
      # - ./node_modules:/usr/src/app/node_modules  Dont Prefare to enable 
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: traffic_db
      MYSQL_USER: deuser
      MYSQL_PASSWORD: default@2025!
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:

#CMD : [docker-compose -f docker-compose.yml up --build -d] 